"""Private, role-owned branch context and learning-group inboxes.

Working transcripts are operational context only.  Nothing in this module can
create or promote a :class:`~evolve.types.CausalMemoryRecord`; promotion remains
the exclusive responsibility of matched-audit services.  Retrieval views name
already-frozen causal-memory artifacts, and learning ownership accepts only a
homogeneous group generated by the same role snapshot.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any, Mapping, Optional, Sequence, Tuple

from evolve.ids import content_id, validate_id
from evolve.types import FrozenDict, LearningGroup, Role, RoleSnapshot

from .adapters import (
    ROLE_STATE_SCHEMA_VERSION,
    RoleIsolationError,
    coerce_role,
    frozen_mapping,
    require_exact_keys,
    require_id,
    require_nonempty,
    require_nonnegative_int,
    require_schema_version,
    thaw_json,
)


WORKING_TRANSCRIPT_VERSION = "role_working_transcript_v1"
RETRIEVAL_VIEW_VERSION = "role_retrieval_view_v1"
LEARNING_OWNERSHIP_VERSION = "role_learning_ownership_v1"


def _optional_id(value: Optional[str], namespace: str, name: str) -> None:
    if value is not None:
        require_id(value, namespace, name)


def _unique(values: Sequence[str], name: str) -> None:
    if len(set(values)) != len(values):
        raise RoleIsolationError(f"{name} must not contain duplicates")


@dataclass(frozen=True)
class RoleWorkingTranscript:
    """Ephemeral branch transcript with an explicit private role owner."""

    run_id: str
    role: Role
    owner_id: str
    branch_id: Optional[str] = None
    entries: Tuple[FrozenDict, ...] = ()
    state_version: str = WORKING_TRANSCRIPT_VERSION
    schema_version: int = ROLE_STATE_SCHEMA_VERSION

    @classmethod
    def create(cls, *, run_id: str, role: Any) -> "RoleWorkingTranscript":
        owner = coerce_role(role)
        require_id(run_id, "run", "run_id")
        owner_id = content_id(
            "role_transcript",
            {
                "state_version": WORKING_TRANSCRIPT_VERSION,
                "run_id": run_id,
                "role": owner.value,
            },
        )
        return cls(run_id=run_id, role=owner, owner_id=owner_id)

    def __post_init__(self) -> None:
        owner = coerce_role(self.role)
        object.__setattr__(self, "role", owner)
        require_id(self.run_id, "run", "run_id")
        require_id(self.owner_id, "role_transcript", "owner_id")
        _optional_id(self.branch_id, "branch", "branch_id")
        require_schema_version(
            self.schema_version, ROLE_STATE_SCHEMA_VERSION, "working transcript"
        )
        if self.state_version != WORKING_TRANSCRIPT_VERSION:
            raise RoleIsolationError(
                f"unsupported working transcript version {self.state_version!r}"
            )
        expected_owner = content_id(
            "role_transcript",
            {
                "state_version": WORKING_TRANSCRIPT_VERSION,
                "run_id": self.run_id,
                "role": owner.value,
            },
        )
        if self.owner_id != expected_owner:
            raise RoleIsolationError("transcript owner_id does not match run/role")
        frozen_entries = []
        for index, entry in enumerate(self.entries):
            frozen = frozen_mapping(entry, f"transcript entries[{index}]")
            if frozen.get("sequence") != index:
                raise RoleIsolationError(
                    "working transcript entries must have contiguous sequence numbers"
                )
            require_nonempty(frozen.get("kind"), f"transcript entries[{index}].kind")
            if "content" not in frozen:
                raise RoleIsolationError(
                    f"transcript entries[{index}] must contain content"
                )
            frozen_entries.append(frozen)
        if frozen_entries and self.branch_id is None:
            raise RoleIsolationError("non-empty working transcript requires a branch_id")
        object.__setattr__(self, "entries", tuple(frozen_entries))

    def start_branch(self, branch_id: str) -> "RoleWorkingTranscript":
        require_id(branch_id, "branch", "branch_id")
        return replace(self, branch_id=branch_id, entries=())

    def append(self, *, kind: str, content: Mapping[str, Any]) -> "RoleWorkingTranscript":
        if self.branch_id is None:
            raise RoleIsolationError("start a branch before appending role transcript entries")
        require_nonempty(kind, "transcript entry kind")
        frozen_content = frozen_mapping(content, "transcript entry content")
        entry = FrozenDict(
            {
                "sequence": len(self.entries),
                "kind": kind,
                "content": frozen_content,
            }
        )
        return replace(self, entries=self.entries + (entry,))

    def clear(self) -> "RoleWorkingTranscript":
        return replace(self, branch_id=None, entries=())

    def to_dict(self) -> Mapping[str, Any]:
        return {
            "record_type": "role_working_transcript",
            "schema_version": self.schema_version,
            "state_version": self.state_version,
            "run_id": self.run_id,
            "role": self.role.value,
            "owner_id": self.owner_id,
            "branch_id": self.branch_id,
            "entries": thaw_json(self.entries),
        }

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "RoleWorkingTranscript":
        keys = (
            "record_type", "schema_version", "state_version", "run_id", "role",
            "owner_id", "branch_id", "entries",
        )
        require_exact_keys(payload, keys, "role working transcript")
        if payload["record_type"] != "role_working_transcript":
            raise RoleIsolationError("invalid role working transcript record_type")
        entries = payload["entries"]
        if not isinstance(entries, (list, tuple)):
            raise RoleIsolationError("working transcript entries must be a list")
        return cls(
            schema_version=payload["schema_version"],
            state_version=payload["state_version"],
            run_id=payload["run_id"],
            role=payload["role"],
            owner_id=payload["owner_id"],
            branch_id=payload["branch_id"],
            entries=tuple(entries),
        )


@dataclass(frozen=True)
class RoleRetrievalView:
    """Frozen contextual view of audit-backed causal memory for one role."""

    run_id: str
    role: Role
    owner_id: str
    view_id: str
    revision: int
    memory_snapshot_id: Optional[str]
    memory_ids: Tuple[str, ...]
    scope: FrozenDict
    state_version: str = RETRIEVAL_VIEW_VERSION
    schema_version: int = ROLE_STATE_SCHEMA_VERSION

    @classmethod
    def create(cls, *, run_id: str, role: Any) -> "RoleRetrievalView":
        owner = coerce_role(role)
        require_id(run_id, "run", "run_id")
        owner_id = content_id(
            "role_retrieval_owner",
            {
                "state_version": RETRIEVAL_VIEW_VERSION,
                "run_id": run_id,
                "role": owner.value,
            },
        )
        scope = FrozenDict()
        view_id = cls._view_id(
            owner_id=owner_id,
            revision=0,
            memory_snapshot_id=None,
            memory_ids=(),
            scope=scope,
        )
        return cls(
            run_id=run_id,
            role=owner,
            owner_id=owner_id,
            view_id=view_id,
            revision=0,
            memory_snapshot_id=None,
            memory_ids=(),
            scope=scope,
        )

    @staticmethod
    def _view_id(
        *,
        owner_id: str,
        revision: int,
        memory_snapshot_id: Optional[str],
        memory_ids: Sequence[str],
        scope: Mapping[str, Any],
    ) -> str:
        return content_id(
            "retrieval_view",
            {
                "state_version": RETRIEVAL_VIEW_VERSION,
                "owner_id": owner_id,
                "revision": revision,
                "memory_snapshot_id": memory_snapshot_id,
                "memory_ids": list(memory_ids),
                "scope": scope,
            },
        )

    def __post_init__(self) -> None:
        owner = coerce_role(self.role)
        object.__setattr__(self, "role", owner)
        require_id(self.run_id, "run", "run_id")
        require_id(self.owner_id, "role_retrieval_owner", "owner_id")
        require_id(self.view_id, "retrieval_view", "view_id")
        require_nonnegative_int(self.revision, "retrieval view revision")
        _optional_id(
            self.memory_snapshot_id,
            "causal_memory_snapshot",
            "memory_snapshot_id",
        )
        memory_ids = tuple(self.memory_ids)
        for memory_id in memory_ids:
            require_id(memory_id, "causal_memory", "memory_ids")
        _unique(memory_ids, "retrieval memory_ids")
        object.__setattr__(self, "memory_ids", memory_ids)
        scope = frozen_mapping(self.scope, "retrieval scope")
        object.__setattr__(self, "scope", scope)
        require_schema_version(
            self.schema_version, ROLE_STATE_SCHEMA_VERSION, "retrieval view"
        )
        if self.state_version != RETRIEVAL_VIEW_VERSION:
            raise RoleIsolationError(
                f"unsupported retrieval view version {self.state_version!r}"
            )
        expected_owner = content_id(
            "role_retrieval_owner",
            {
                "state_version": RETRIEVAL_VIEW_VERSION,
                "run_id": self.run_id,
                "role": owner.value,
            },
        )
        if self.owner_id != expected_owner:
            raise RoleIsolationError("retrieval owner_id does not match run/role")
        expected_view = self._view_id(
            owner_id=self.owner_id,
            revision=self.revision,
            memory_snapshot_id=self.memory_snapshot_id,
            memory_ids=memory_ids,
            scope=scope,
        )
        if self.view_id != expected_view:
            raise RoleIsolationError("retrieval view_id does not match frozen content")

    def advance(
        self,
        *,
        memory_snapshot_id: Optional[str],
        memory_ids: Sequence[str],
        scope: Mapping[str, Any],
    ) -> "RoleRetrievalView":
        _optional_id(memory_snapshot_id, "causal_memory_snapshot", "memory_snapshot_id")
        identifiers = tuple(memory_ids)
        for memory_id in identifiers:
            require_id(memory_id, "causal_memory", "memory_ids")
        _unique(identifiers, "retrieval memory_ids")
        frozen_scope = frozen_mapping(scope, "retrieval scope")
        if (
            memory_snapshot_id == self.memory_snapshot_id
            and identifiers == self.memory_ids
            and frozen_scope == self.scope
        ):
            raise RoleIsolationError(
                "retrieval view version may advance only when its content changes"
            )
        revision = self.revision + 1
        view_id = self._view_id(
            owner_id=self.owner_id,
            revision=revision,
            memory_snapshot_id=memory_snapshot_id,
            memory_ids=identifiers,
            scope=frozen_scope,
        )
        return replace(
            self,
            view_id=view_id,
            revision=revision,
            memory_snapshot_id=memory_snapshot_id,
            memory_ids=identifiers,
            scope=frozen_scope,
        )

    def to_dict(self) -> Mapping[str, Any]:
        return {
            "record_type": "role_retrieval_view",
            "schema_version": self.schema_version,
            "state_version": self.state_version,
            "run_id": self.run_id,
            "role": self.role.value,
            "owner_id": self.owner_id,
            "view_id": self.view_id,
            "revision": self.revision,
            "memory_snapshot_id": self.memory_snapshot_id,
            "memory_ids": list(self.memory_ids),
            "scope": thaw_json(self.scope),
        }

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "RoleRetrievalView":
        keys = (
            "record_type", "schema_version", "state_version", "run_id", "role",
            "owner_id", "view_id", "revision", "memory_snapshot_id", "memory_ids",
            "scope",
        )
        require_exact_keys(payload, keys, "role retrieval view")
        if payload["record_type"] != "role_retrieval_view":
            raise RoleIsolationError("invalid role retrieval view record_type")
        memory_ids = payload["memory_ids"]
        if not isinstance(memory_ids, (list, tuple)):
            raise RoleIsolationError("retrieval memory_ids must be a list")
        return cls(
            schema_version=payload["schema_version"],
            state_version=payload["state_version"],
            run_id=payload["run_id"],
            role=payload["role"],
            owner_id=payload["owner_id"],
            view_id=payload["view_id"],
            revision=payload["revision"],
            memory_snapshot_id=payload["memory_snapshot_id"],
            memory_ids=tuple(memory_ids),
            scope=payload["scope"],
        )


@dataclass(frozen=True)
class RoleLearningOwnership:
    """IDs of homogeneous persisted groups claimed by one role only."""

    run_id: str
    role: Role
    owner_id: str
    group_ids: Tuple[str, ...] = ()
    state_version: str = LEARNING_OWNERSHIP_VERSION
    schema_version: int = ROLE_STATE_SCHEMA_VERSION

    @classmethod
    def create(cls, *, run_id: str, role: Any) -> "RoleLearningOwnership":
        owner = coerce_role(role)
        require_id(run_id, "run", "run_id")
        owner_id = content_id(
            "role_learning_owner",
            {
                "state_version": LEARNING_OWNERSHIP_VERSION,
                "run_id": run_id,
                "role": owner.value,
            },
        )
        return cls(run_id=run_id, role=owner, owner_id=owner_id)

    def __post_init__(self) -> None:
        owner = coerce_role(self.role)
        object.__setattr__(self, "role", owner)
        require_id(self.run_id, "run", "run_id")
        require_id(self.owner_id, "role_learning_owner", "owner_id")
        groups = tuple(self.group_ids)
        for group_id in groups:
            require_id(group_id, "learning_group", "group_ids")
        _unique(groups, "role learning group_ids")
        object.__setattr__(self, "group_ids", groups)
        require_schema_version(
            self.schema_version, ROLE_STATE_SCHEMA_VERSION, "learning ownership"
        )
        if self.state_version != LEARNING_OWNERSHIP_VERSION:
            raise RoleIsolationError(
                f"unsupported learning ownership version {self.state_version!r}"
            )
        expected = content_id(
            "role_learning_owner",
            {
                "state_version": LEARNING_OWNERSHIP_VERSION,
                "run_id": self.run_id,
                "role": owner.value,
            },
        )
        if self.owner_id != expected:
            raise RoleIsolationError("learning owner_id does not match run/role")

    def claim(
        self,
        *,
        group: LearningGroup,
        snapshot: RoleSnapshot,
    ) -> "RoleLearningOwnership":
        if group.role != self.role or snapshot.role != self.role:
            raise RoleIsolationError("a role cannot claim another role's learning group")
        if group.policy_snapshot_id != snapshot.snapshot_id:
            raise RoleIsolationError(
                "learning group policy snapshot does not match the claimed role snapshot"
            )
        if group.group_id in self.group_ids:
            return self
        return replace(self, group_ids=self.group_ids + (group.group_id,))

    def clear(self) -> "RoleLearningOwnership":
        return replace(self, group_ids=())

    def to_dict(self) -> Mapping[str, Any]:
        return {
            "record_type": "role_learning_ownership",
            "schema_version": self.schema_version,
            "state_version": self.state_version,
            "run_id": self.run_id,
            "role": self.role.value,
            "owner_id": self.owner_id,
            "group_ids": list(self.group_ids),
        }

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "RoleLearningOwnership":
        keys = (
            "record_type", "schema_version", "state_version", "run_id", "role",
            "owner_id", "group_ids",
        )
        require_exact_keys(payload, keys, "role learning ownership")
        if payload["record_type"] != "role_learning_ownership":
            raise RoleIsolationError("invalid role learning ownership record_type")
        groups = payload["group_ids"]
        if not isinstance(groups, (list, tuple)):
            raise RoleIsolationError("role learning group_ids must be a list")
        return cls(
            schema_version=payload["schema_version"],
            state_version=payload["state_version"],
            run_id=payload["run_id"],
            role=payload["role"],
            owner_id=payload["owner_id"],
            group_ids=tuple(groups),
        )


__all__ = [
    "LEARNING_OWNERSHIP_VERSION",
    "RETRIEVAL_VIEW_VERSION",
    "WORKING_TRANSCRIPT_VERSION",
    "RoleLearningOwnership",
    "RoleRetrievalView",
    "RoleWorkingTranscript",
]
